/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ntu_sdp2_painthelper_capture_NativeEdgeDetector */

#ifndef _Included_com_ntu_sdp2_painthelper_capture_NativeEdgeDetector
#define _Included_com_ntu_sdp2_painthelper_capture_NativeEdgeDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ntu_sdp2_painthelper_capture_NativeEdgeDetector
 * Method:    nativeDetectEdge
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ntu_sdp2_painthelper_capture_NativeEdgeDetector_nativeDetectEdge
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
