/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ntu_sdp2_painthelper_utils_NativeImgProcessor */

#ifndef _Included_com_ntu_sdp2_painthelper_utils_NativeImgProcessor
#define _Included_com_ntu_sdp2_painthelper_utils_NativeImgProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ntu_sdp2_painthelper_utils_NativeImgProcessor
 * Method:    nativeBlur
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_ntu_sdp2_painthelper_utils_NativeImgProcessor_nativeBlur
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_ntu_sdp2_painthelper_utils_NativeImgProcessor
 * Method:    nativeBilateralFilter
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_ntu_sdp2_painthelper_utils_NativeImgProcessor_nativeBilateralFilter
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_ntu_sdp2_painthelper_utils_NativeImgProcessor
 * Method:    nativeAdaptiveThres
 * Signature: (JJIIIII)V
 */
JNIEXPORT void JNICALL Java_com_ntu_sdp2_painthelper_utils_NativeImgProcessor_nativeAdaptiveThres
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     com_ntu_sdp2_painthelper_utils_NativeImgProcessor
 * Method:    nativeSkeletonize
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ntu_sdp2_painthelper_utils_NativeImgProcessor_nativeSkeletonize
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_ntu_sdp2_painthelper_utils_NativeImgProcessor
 * Method:    nativeDilate
 * Signature: (JJIII)V
 */
JNIEXPORT void JNICALL Java_com_ntu_sdp2_painthelper_utils_NativeImgProcessor_nativeDilate
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint);

/*
 * Class:     com_ntu_sdp2_painthelper_utils_NativeImgProcessor
 * Method:    nativeInvert
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ntu_sdp2_painthelper_utils_NativeImgProcessor_nativeInvert
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
